#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=01:00:00

# parse config.json to load the input parameters needed for the app
t1=$(jq -r .t1 config.json)

# run the actual python code
./main.m $t1
